name: Unit Test Java

on:
  push:
    branches:
      - feature-jv1
      - feature-jv2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Lấy code từ GitHub
        uses: actions/checkout@v3

      - name: Cài Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dịch code bằng Maven
        run: mvn clean install

      - name: Chạy Unit Test
        run: mvn test
